apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-deployment

# Deployment specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  
  # Define pod we want to deploy
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: spring-container
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CASSANDRA_CONTACT_POINTS   # overrides application.properties
              value: "cassandra.cassandra.svc.cluster.local"
            - name: SPRING_CASSANDRA_PORT
              value: "9042"
            - name: SPRING_CASSANDRA_KEYSPACE_NAME
              value: "url_shortener"
            - name: SPRING_CASSANDRA_LOCAL_DATACENTER
              value: "datacenter1"
          
          



