apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-deployment

# Deployment specification
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  
  # Define pod we want to deploy
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: spring-container
          image: spring-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          



