spring:
  application:
    name: url_shortener
  
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: url_shortener
    local-datacenter: datacenter1
    schema-action: NONE

server:
  port: 8080