apiVersion: apps/v1
kind: Deployment

metadata:
  name: consumer-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app

  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-container
          image: url-write-consumer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "3.87.112.165:9092"
            - name: SPRING_CASSANDRA_CONTACT_POINTS
              value: "cassandra.cassandra.svc.cluster.local"
            - name: SPRING_CASSANDRA_PORT
              value: "9042"
            - name: SPRING_CASSANDRA_KEYSPACE_NAME
              value: "url_shortener"
            - name: SPRING_CASSANDRA_LOCAL_DATACENTER
              value: "datacenter1"
