apiVersion: apps/v1
kind: Deployment

metadata:
  name: consumer-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app

  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-container
          image: url-write-consumer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "3.80.85.4:9092"
