apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica-deployment
  namespace: redis
spec:
  replicas: 2                  # scale replicas 
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args: ["--replicaof", "redis-primary-service", "6379"]  # points to primary