apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary-deployment
  namespace: redis
spec:
  replicas: 1   # Primary Redis instance
  selector:
    matchLabels:
      app: redis
      role: primary
  template:
    metadata:
      labels:
        app: redis
        role: primary
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args: ["--appendonly", "yes"]  # Enable persistence